version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: catalog-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: cataloguser
      POSTGRES_PASSWORD: catalogpass
      POSTGRES_DB: catalog_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cataloguser -d catalog_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: catalog-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE: postgresql://cataloguser:catalogpass@db:5432/catalog_db
      PORT: 8080
      SERVER_PORT: 8080
    ports:
      - "80:8080"
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  postgres_data:
